[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04e29c9713086b61ba8045c247182ea9d6f14e8b"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "6aaf034d44f6a261a94da49ace4c54f4e845c148a50a8e70f203edc8a93d62c0"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha1+0/libhelfem.v0.0.1-alpha1.i686-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d9427e43144be345693f80eefd66e1635de259b"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "4e651fbdc268aef71a72fd6ab5e0ef87e9f494f90aa7a5977eafa0683efd6c6e"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha2+0/libhelfem.v0.0.1-alpha2.x86_64-linux-gnu-cxx11.tar.gz"
