[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04e29c9713086b61ba8045c247182ea9d6f14e8b"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "6aaf034d44f6a261a94da49ace4c54f4e845c148a50a8e70f203edc8a93d62c0"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha1+0/libhelfem.v0.0.1-alpha1.i686-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05dc192d94529e9eb7e63c3a76e6fb5ef8067915"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "dc555202a68b918a0205af65b66539505b82b05cb1b9802157327eed0cc360b2"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha4+0/libhelfem.v0.0.1-alpha4.x86_64-linux-gnu-cxx11.tar.gz"
