[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c699ae41fd25e1a1b08dad5589c6db001c1abed9"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "2cd2e0343f3d7af8054c882f9ac0720533d4129f0922951feceae06a0087a774"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha6+0/libhelfem.v0.0.1-alpha6.i686-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c92a1f4e0c7cfcf13d19b3285e839065f817cce"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "1fd8b79ee3685db3403e6f342b81f98cd828b76c28ff5f281742d104e206ac68"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha6+0/libhelfem.v0.0.1-alpha6.x86_64-linux-gnu-cxx11.tar.gz"
