[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105e8e7d190093fe4d8b9420f19cee18ab018120"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "9197092f887109abb73806035b6e5643e188b8b4372cc01c85478fdb2d994235"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha7+0/libhelfem.v0.0.1-alpha7.i686-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ae3139ab909c20a61d7f25dcc57575ae0c78614"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "a847bb93afde3089c4d99c6d495550fef1a6d0013679f0d9482b2f108bf98d05"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha7+0/libhelfem.v0.0.1-alpha7.x86_64-linux-gnu-cxx11.tar.gz"
