[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04e29c9713086b61ba8045c247182ea9d6f14e8b"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "6aaf034d44f6a261a94da49ace4c54f4e845c148a50a8e70f203edc8a93d62c0"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha1+0/libhelfem.v0.0.1-alpha1.i686-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d5033d227042337fb259352bf4bcf7d1387738c"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "ce9a596d5cf8397d53b4df73bf7e9e373cbc4217bfb950f2c326c55ef34419b2"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.1-alpha2+0/libhelfem.v0.0.1-alpha2.x86_64-linux-gnu-cxx11.tar.gz"
