[[libhelfem]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "508dbedb65f437095fb360916d0aff4150144132"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "39cca050eeca9d565ad53657c6c787233afe9f541745e8b2868d8a4e19eb1127"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.aarch64-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef8c2579f68e244e56dbd5e220d8631ed098347e"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "275d3c64e26a4789ed3a961eae4e587827828943d5157efb71c67e33f279e62c"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4569c40f1365464a50d9cb7f5e1d097113813ac"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "3f53a73e820bbfa29990126c6a7d3be803a299471f4dcc6864ef3b8e304bfc64"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.i686-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58d5d70305a8c0ceee37fab1cdb6271eb00816a9"
os = "windows"

    [[libhelfem.download]]
    sha256 = "32838165770a59c557cde82fcb5abc34fd56f900e4fa79649279add8b5effed8"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.i686-w64-mingw32-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eff04310ecdf338855a27ce9f48fe4d025847e2"
os = "macos"

    [[libhelfem.download]]
    sha256 = "27de03519785b9b80646425076c3293181d8c4f1037661216c19f4007e88bd74"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4accaaf60f4b1e8a4ad2925efb97621ce3a0f7af"
libc = "glibc"
os = "linux"

    [[libhelfem.download]]
    sha256 = "394050da9e356c1629dc880523e03c1b5151b584334019c0deb7c8c6a2e26d70"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.x86_64-linux-gnu-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03c07b4e39d530c9e93d421ef50b3a8a29dac25a"
os = "freebsd"

    [[libhelfem.download]]
    sha256 = "2aa243377ad9945ebef0b174d2e502521a52ba1a3ce5117559ffea7a42feb7c7"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[libhelfem]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a5ca685a4117b78143d76ae0da74ab47de9e670"
os = "windows"

    [[libhelfem.download]]
    sha256 = "9a938093dc8fe72b6d548ce012925cd1aad0f86ed8f4b937c3f0c4fb65689834"
    url = "https://github.com/mortenpi/libhelfem_jll.jl/releases/download/libhelfem-v0.0.2-alpha1+2/libhelfem.v0.0.2-alpha1.x86_64-w64-mingw32-cxx11.tar.gz"
